### ISSUE TITLE
How can I attach spot workers to cluster?

### ISSUE THREAD

**Issue by frcho** [marcincuber/eks#1]
Hello, I'm looking your settings in the latest configurations which available in terraform-aws, and I realize the deployment, I can see every was deploy.
I have 3 m5  Spot instances running, and the eks cluster too

But when I run kubectl get nodes

This is the ouput.

**No resources found in default namespace.**

What is the right process to achieve the  **kubectl get nodes**  show me the spot instances?

Maybe, Can you help with that?, I feel a little lost and I really need your help for achieve that.

Thank you.

**Comment by marcincuber** [comment]
@frcho With my templates you already have nicely configured spot worker nodes using launch templates + auto scaling group. You can enable them by setting variable `enable_spot_workers` to `true`. Take a look at `spot-worker-nodes.tf` it should give you a good idea how it all works. Cloudformation template used to control spot instances can be found in `cfm/worker-node-spot-stack.yaml`.

I wouldn't recommend using eks module since you simply not going to have a rollingUpdate ability by using only terraform. Also, using spot fleet is not needed, much better alternative is to use launch templates + asg. 

For nodes to join remember that you need to configure configmap `aws-auth` which is stored in `kube-system` namespace. This is configured with templates stored in `terraform-k8s` folder.
